/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  documentationSidebar: [
    {
      type: 'doc',
      label: 'Overview',
      id: 'docs/index',
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [{type: 'autogenerated', dirName: 'docs/getting-started'}],
    },
    {
      type: 'doc',
      label: 'API Reference',
      id: 'docs/api',
    },
    {
      type: 'category',
      label: 'Developers',
      items: [{type: 'autogenerated', dirName: 'docs/developers'}],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [{type: 'autogenerated', dirName: 'docs/contributing'}],
    }
  ],
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorials'}],
};

export default sidebars;
